### ISSUE TITLE
Increase content max width

### ISSUE THREAD

**Issue by andodet** [andodet/anddt#1]
Theme is 'too minimal': lots of horizontal space is wasted in favor of vertical scrolling.
**todo**: incerase `max-body-width` to use some horizontal space:

```css
  .max-body-width {
    padding-left: 10px;
    width: 1000px;
    padding-right: 10px;
  }
}
```
